name: Django CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysqldb:
        image: mysql:latest
        env:
           MYSQL_USER: root
           MYSQL_PASSWORD: 1234
           MYSQL_DATABASE: db,
           MYSQL_ROOT_PASSWORD: 1234
        ports:
          - 3306:3306
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Start Pytest
      run: |
        pytest
